### PR TITLE
MNT: Use Jinja2 set statement for python_min

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Using a Jinja2 `set` statement for the `python_min` allows for all the build metadata to be contained in the `recipe/meta.yaml` and for `recipe/conda_build_config.yaml` to be removed.
* Bump build number.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [N/A] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
cc @jonas-eschle this is an easier way than what I showed in PR #28.

**Comment by matthewfeickert** [comment]
Need to figure out why the linter message won't go away though.

**Comment by matthewfeickert** [comment]
> * If the package requires a newer Python version than the currently supported minimum version on `conda-forge`, you can override the `python_min` variable by adding a Jinja2 `set` statement at the top of your recipe (or using an equivalent `context` variable for v1 recipes).

Ah, I think `conda-smithy` is only checking if `python_min` is **newer** than the map value of `python_min` in `.ci_support/linux_64_.yaml`. That's not what I care about though (for this PR), I want it to be the oldest possible value that corresponds to 

```toml
[project]
...
requires-python = ">=3.7"
```

in [the Python package's `pyproject.toml`](https://github.com/scikit-hep/pyhf/blob/b500270c6a7744d16b481dfda247c066ef3c2cb4/pyproject.toml#L14), which may also be a Python version dropped from conda-forge global pinning support.

**Comment by jonas-eschle** [comment]
> cc @jonas-eschle this is an easier way than what I showed in PR #28.

Thanks for the ping, yes, looks preferrable

**Comment by matthewfeickert** [comment]
Once https://github.com/conda-forge/conda-smithy/pull/2132 is merged this can get rerendered and then should be good to go.

**Review by kratsg — APPROVED** [review]

**Comment by matthewfeickert** [comment]
https://github.com/conda-forge/conda-smithy/pull/2132 is merged, but we need to wait for [`conda-smithy` release `v3.44.4`](https://github.com/conda-forge/conda-smithy/releases/tag/v3.44.4) with the fix in there.

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
